security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: user_provider

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
